### ISSUE TITLE
Consolidate Migration Scripts

### ISSUE THREAD

**Issue by tmrowe** [ministryofjustice/apvs-internal-web#149]
We have a large number of scripts at this point, many of them simple making minor changes to table functions that require the functions definition to be duplicated. 

We should rewrite the migrations removing as many intermediate migrations as possible from both external and internal web. 

Once the migrations are rewritten we will need to drop the tables and functions on our test and dev environments and then redeploy the application.

**TODO:**
- [x] Create seed scripts to drop then recreate each table function
- [x] Update scripts section in package.json to run the seed function after migration
- [x] Update migration README on internal/external web to reflect change in migration process
- [ ] Update CI config so that table functions are dropped/recreated when rolling migrations up or down
- [x] Consolidate External Web migrations.
- [x] Consolidate Internal Web migrations.

**Comment by gdouglas1** [comment]
To be done:
- Create seed scripts to drop then recreate each table function
- Update migration README on internal/external web to reflect change in migration process
- Update CI config so that table functions are dropped/recreated when rolling migrations up or down
